[package]
build = "build.rs"
edition = "2021"
name = "substrix"
version = "0.1.0"

[[bin]]
bench = false
name = "substrix"
test = false

[dependencies]

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
