[package]
edition = "2024"
name = "substrix"
version = "0.1.0"

[dependencies]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[build-dependencies]
cc = "1.0"
